### ISSUE TITLE
Getting type error

### ISSUE THREAD

**Issue by pratikbaid3** [mehdizarepour/lodash_dart#1]
```dart
Map<String, dynamic> map = { };

    map = gato.set(map, 'a.c.d.e', 2);
```

When I try to change element at depth 3 or higher I get a type error

```
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("d")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      set (package:gato/src/set.dart:27:21)
#2      set (package:gato/src/set.dart:27:14)
#3      set (package:gato/src/set.dart:27:14)
#4      main (package:flood_mobile/Playground/test_create_file_folder_structure.dart:23:11)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

This works fine when the depth is 2 ie:a.b

**Comment by pratikbaid3** [comment]
Are there some limitations as to how nested the map could be?

**Comment by mehdizarepour** [comment]
Hi @pratikbaid3, thanks for opening this issue.
No, there aren’t any limitations, I’m not in my office right now, I will check and let you know about it.

**Comment by mehdizarepour** [comment]
@pratikbaid3 Yes you were right, but it's not because of the `path` arg, It happens when the `map` arg is `{}` or `null`.

**Comment by mehdizarepour** [comment]
@pratikbaid3 I've solved this issue, now you can have changes in `v0.0.4` and you can see this test [test](https://github.com/mehdizarepour/gato/blob/4cdf38b3a697d4c0ce0fc7f676856413dd5926e6/test/gato.dart#L51) for an example.

https://github.com/mehdizarepour/gato/blob/4cdf38b3a697d4c0ce0fc7f676856413dd5926e6/test/gato.dart#L51-L56

Please close this issue or let me know if you still have any problems.
Thanks.

**Comment by pratikbaid3** [comment]
@mehdizarepour The issue seems to have been fixed now. Thanks.

**Comment by JiboStore** [comment]
This issue is still happening if object in the middle of the path does not exist, example:

```
var map = { "a": { "b": {"f": "g"} } }
```
`gato.get(map, 'a.b.c.d')` will throw the error

**Comment by mehdizarepour** [comment]
Hi, @JiboStore.
It seems like to be a different issue! Can you please open a new issue?

**Comment by mehdizarepour** [comment]
Hi, @JiboStore.
The new update is available on `v0.0.5` and the problem is fixed.
